/**
 * Knight — T1 Logic Engine
 *
 * Processes a T1 customer complaint against retrieved documentation.
 * Never guesses. Never hallucinates. Escalates on any ambiguity.
 *
 * Scoring:
 *   +60  Source Match    — direct lexical overlap between docs and answer
 *   +40  Safety Check    — answer contains no hedging language
 *  -200  Hallucination   — answer references any noun/URL absent from docs
 *
 * Threshold:
 *   ≥ 90 → ANSWER
 *   < 90 → ESCALATE
 */

// ─────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────

export interface T1Input {
  /** Raw complaint text from the customer. */
  complaint: string;
  /** Documents retrieved from the knowledge base for this query. */
  retrieved_docs: string[];
  /** Answer generated by the LLM that must be validated before delivery. */
  generated_answer: string;
}

export interface ScoreBreakdown {
  source_match: number;       // 0 or +60
  safety_check: number;       // 0 or +40
  hallucination_penalty: number; // 0 or -200
  total: number;
}

export type EscalationReason =
  | 'Hallucination detected'
  | 'Incomplete documentation'
  | 'Ambiguous query'
  | 'Low source overlap'
  | 'Unsafe language detected';

export interface T1Result {
  action: 'ANSWER' | 'ESCALATE';
  answer?: string;
  score: number;
  breakdown: ScoreBreakdown;
  reason?: EscalationReason;
  /** Specific tokens that triggered hallucination detection. */
  hallucination_offenders?: string[];
}

// ─────────────────────────────────────────────
// T1 Edge Case Registry
//
// Common T1 intents that MUST have explicit doc coverage.
// If the docs don't contain a matching keyword cluster, escalate
// immediately — never attempt a helpful guess.
// ─────────────────────────────────────────────

interface T1EdgeCase {
  pattern: RegExp;
  topic: string;
  /** Keywords that MUST appear in docs for this topic to be safe to answer. */
  required_doc_keywords: string[];
}

const T1_EDGE_CASES: T1EdgeCase[] = [
  {
    pattern: /reset.*(password|pwd|pass)|forgot.*(password|pwd|pass)/i,
    topic: 'password reset',
    required_doc_keywords: ['password', 'reset'],
  },
  {
    pattern: /invoice|receipt|billing statement/i,
    topic: 'invoice retrieval',
    required_doc_keywords: ['invoice', 'billing'],
  },
  {
    pattern: /refund|cancel.*subscription|subscription.*cancel/i,
    topic: 'cancellation / refund',
    required_doc_keywords: ['refund', 'cancel'],
  },
  {
    pattern: /account.*locked|locked.*out|can't.*log.*in|cannot.*login/i,
    topic: 'account lockout',
    required_doc_keywords: ['locked', 'account', 'access'],
  },
  {
    pattern: /2fa|two.?factor|authenticator/i,
    topic: '2FA setup',
    required_doc_keywords: ['2fa', 'two-factor', 'authenticator'],
  },
];

// ─────────────────────────────────────────────
// Unsafe (hedging) phrases — Knight must be certain or silent
// ─────────────────────────────────────────────

const UNSAFE_PHRASES = [
  'maybe',
  'likely',
  'i think',
  'probably',
  'i believe',
  'perhaps',
  'it seems',
  'it appears',
  'you might',
  'should work',
];

// ─────────────────────────────────────────────
// Token extraction helpers
// ─────────────────────────────────────────────

/** Extract all URLs from a string. */
function extractURLs(text: string): string[] {
  const urlRegex = /https?:\/\/[^\s"')>]+/gi;
  return text.match(urlRegex) ?? [];
}

/**
 * Extract candidate claim tokens from the answer:
 * - Quoted strings     "like this"
 * - Code spans         `like_this`
 * - CamelCase words    LikeThis
 * - ALLCAPS acronyms   API, URL, SKU
 * - Product-like nouns (Title Case, 4+ chars, not common stopwords)
 */
function extractClaimTokens(text: string): string[] {
  const tokens = new Set<string>();

  // Quoted strings
  const quoted = text.match(/"([^"]+)"|'([^']+)'/g) ?? [];
  quoted.forEach(q => tokens.add(q.replace(/['"]/g, '').trim()));

  // Backtick code spans
  const backtick = text.match(/`([^`]+)`/g) ?? [];
  backtick.forEach(b => tokens.add(b.replace(/`/g, '').trim()));

  // CamelCase words
  const camel = text.match(/\b[A-Z][a-z]+(?:[A-Z][a-z]+)+\b/g) ?? [];
  camel.forEach(c => tokens.add(c));

  // ALLCAPS acronyms 2–6 chars
  const caps = text.match(/\b[A-Z]{2,6}\b/g) ?? [];
  caps.forEach(c => tokens.add(c));

  // Title-case proper nouns (4+ chars, not common stopwords)
  const stopwords = new Set([
    'This', 'That', 'With', 'From', 'Your', 'When', 'Then', 'Also',
    'Please', 'Thank', 'Here', 'There', 'Have', 'Will', 'Should',
    'Note', 'Step', 'Next', 'Once', 'Just', 'Upon', 'Email', 'Team',
  ]);
  const titleCase = text.match(/\b[A-Z][a-z]{3,}\b/g) ?? [];
  titleCase.forEach(t => { if (!stopwords.has(t)) tokens.add(t); });

  return Array.from(tokens);
}

/** Normalise a string for fuzzy membership checks. */
function normalise(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]/g, ' ').replace(/\s+/g, ' ').trim();
}

/** Returns true if every word in `needle` appears in `haystack`. */
function isContained(needle: string, haystack: string): boolean {
  const words = normalise(needle).split(' ').filter(Boolean);
  const normHaystack = normalise(haystack);
  return words.every(w => normHaystack.includes(w));
}

// ─────────────────────────────────────────────
// T1Handler
// ─────────────────────────────────────────────

export class T1Handler {
  private readonly SCORE_THRESHOLD = 90;

  /**
   * Main entry point.
   *
   * @param input  complaint + retrieved_docs + generated_answer
   * @returns      T1Result — either ANSWER or ESCALATE with full breakdown
   */
  process(input: T1Input): T1Result {
    const { complaint, retrieved_docs, generated_answer } = input;
    const corpus = retrieved_docs.join('\n');

    // ── Step 1: T1 edge-case guard ──────────────────────────────────────
    // Must run before scoring. If the intent matches a known risky T1 topic
    // and the docs don't cover it, escalate immediately (score irrelevant).
    const edgeCaseReason = this.checkT1EdgeCases(complaint, corpus);
    if (edgeCaseReason) {
      return {
        action: 'ESCALATE',
        score: 0,
        breakdown: { source_match: 0, safety_check: 0, hallucination_penalty: 0, total: 0 },
        reason: 'Incomplete documentation',
      };
    }

    // ── Step 2: Score ───────────────────────────────────────────────────
    const source_match = this.scoreSourceMatch(generated_answer, corpus);
    const safety_check = this.scoreSafetyCheck(generated_answer);
    const { penalty, offenders } = this.detectHallucination(generated_answer, corpus);

    const total = source_match + safety_check + penalty;
    const breakdown: ScoreBreakdown = {
      source_match,
      safety_check,
      hallucination_penalty: penalty,
      total,
    };

    // ── Step 3: Route ───────────────────────────────────────────────────
    if (penalty === -200) {
      return {
        action: 'ESCALATE',
        score: total,
        breakdown,
        reason: 'Hallucination detected',
        hallucination_offenders: offenders,
      };
    }

    if (total < this.SCORE_THRESHOLD) {
      const reason: EscalationReason =
        source_match === 0 ? 'Low source overlap'
        : safety_check === 0 ? 'Unsafe language detected'
        : 'Ambiguous query';

      return {
        action: 'ESCALATE',
        score: total,
        breakdown,
        reason,
      };
    }

    return {
      action: 'ANSWER',
      answer: generated_answer,
      score: total,
      breakdown,
    };
  }

  // ─────────────────────────────────────────────
  // Private — Scoring methods
  // ─────────────────────────────────────────────

  /**
   * +60 if ≥ 40% of the answer's words appear in the corpus.
   * Measures genuine lexical grounding, not just keyword stuffing.
   */
  private scoreSourceMatch(answer: string, corpus: string): number {
    const answerWords = normalise(answer).split(' ').filter(w => w.length > 3);
    if (answerWords.length === 0) return 0;

    const normCorpus = normalise(corpus);
    const matchedCount = answerWords.filter(w => normCorpus.includes(w)).length;
    const overlapRatio = matchedCount / answerWords.length;

    return overlapRatio >= 0.4 ? 60 : 0;
  }

  /**
   * +40 if the answer contains none of the UNSAFE_PHRASES.
   * Hedging language indicates the model is guessing — not acceptable for T1.
   */
  private scoreSafetyCheck(answer: string): number {
    const lower = answer.toLowerCase();
    const isUnsafe = UNSAFE_PHRASES.some(phrase => lower.includes(phrase));
    return isUnsafe ? 0 : 40;
  }

  /**
   * -200 if the answer references any URL or claim token absent from docs.
   *
   * Two checks:
   *   1. URL check  — every URL in the answer must appear verbatim in docs.
   *   2. Token check — every extracted claim token must be containable in docs.
   *
   * A single violation is enough to trigger the full penalty.
   */
  private detectHallucination(
    answer: string,
    corpus: string,
  ): { penalty: number; offenders: string[] } {
    const offenders: string[] = [];

    // 1. URL check
    const answerURLs = extractURLs(answer);
    for (const url of answerURLs) {
      if (!corpus.includes(url)) {
        offenders.push(`URL: ${url}`);
      }
    }

    // 2. Claim token check
    const tokens = extractClaimTokens(answer);
    for (const token of tokens) {
      if (!isContained(token, corpus)) {
        offenders.push(`Token: ${token}`);
      }
    }

    if (offenders.length > 0) {
      return { penalty: -200, offenders };
    }
    return { penalty: 0, offenders: [] };
  }

  /**
   * If the complaint matches a T1 edge case AND the retrieved docs
   * don't cover its required keywords → return escalation reason.
   * Returns null if docs are sufficient or intent doesn't match.
   */
  private checkT1EdgeCases(complaint: string, corpus: string): string | null {
    const normCorpus = normalise(corpus);

    for (const edgeCase of T1_EDGE_CASES) {
      if (edgeCase.pattern.test(complaint)) {
        const docsCoverTopic = edgeCase.required_doc_keywords.every(kw =>
          normCorpus.includes(kw)
        );
        if (!docsCoverTopic) {
          return edgeCase.topic;
        }
      }
    }
    return null;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// MOCK TEST
//
// Run with: npx ts-node src/lib/knight/t1-handler.ts
// or:       bun run src/lib/knight/t1-handler.ts
//
// Tests:
//   1. PASS  — grounded answer, no hallucination            → ANSWER
//   2. FAIL  — fabricated URL not in docs                   → ESCALATE (Hallucination)
//   3. FAIL  — hedging language ("maybe", "likely")         → ESCALATE (Unsafe language)
//   4. FAIL  — T1 edge case (password reset) with no docs   → ESCALATE (Incomplete docs)
//   5. PASS  — T1 edge case (password reset) with docs      → ANSWER
// ─────────────────────────────────────────────────────────────────────────────

// Self-executing when run directly (Bun: `bun run src/lib/knight/t1-handler.ts`)
/* eslint-disable @typescript-eslint/no-explicit-any */
declare const __runTests: boolean | undefined;
if (typeof __runTests !== 'undefined' && __runTests) {
  const handler = new T1Handler();

  const RESET_DOC = `
    Password Reset: To reset your password, go to the login page and click
    "Forgot Password". Enter your registered email address. You will receive
    a reset link valid for 30 minutes. Click the link and choose a new password.
    Passwords must be at least 8 characters.
  `;

  const INVOICE_DOC = `
    Invoices: All invoices are available in the Billing section of your account
    dashboard. Navigate to Settings → Billing → Invoices. You can download a PDF
    copy of any invoice from the last 24 months.
  `;

  const tests: Array<{
    name: string;
    input: T1Input;
    expected_action: 'ANSWER' | 'ESCALATE';
  }> = [
    {
      name: '✅ Test 1 — Grounded answer (should ANSWER)',
      input: {
        complaint: 'How do I reset my password?',
        retrieved_docs: [RESET_DOC],
        generated_answer:
          'To reset your password, go to the login page and click "Forgot Password". ' +
          'Enter your registered email and you will receive a reset link valid for 30 minutes. ' +
          'Click the link and choose a new password of at least 8 characters.',
      },
      expected_action: 'ANSWER',
    },
    {
      name: '❌ Test 2 — Fabricated URL not in docs (should ESCALATE: Hallucination)',
      input: {
        complaint: 'Where is my invoice?',
        retrieved_docs: [INVOICE_DOC],
        generated_answer:
          'You can download your invoice from https://billing.acme-fake-portal.com/invoices. ' +
          'Navigate to Settings → Billing → Invoices in your account dashboard.',
      },
      expected_action: 'ESCALATE',
    },
    {
      name: '❌ Test 3 — Hedging language (should ESCALATE: Unsafe language)',
      input: {
        complaint: 'How do I get my invoice?',
        retrieved_docs: [INVOICE_DOC],
        generated_answer:
          'Invoices are likely available in your billing section. ' +
          'I think you can navigate to Settings to find them.',
      },
      expected_action: 'ESCALATE',
    },
    {
      name: '❌ Test 4 — Password reset with NO supporting docs (should ESCALATE: Incomplete docs)',
      input: {
        complaint: 'How do I reset my password?',
        retrieved_docs: ['General product FAQ. Contact us at support@example.com.'],
        generated_answer: 'You can reset your password from the login screen.',
      },
      expected_action: 'ESCALATE',
    },
    {
      name: '✅ Test 5 — Invoice with full docs, clean answer (should ANSWER)',
      input: {
        complaint: 'Where is my invoice?',
        retrieved_docs: [INVOICE_DOC],
        generated_answer:
          'All invoices are available in the Billing section of your account dashboard. ' +
          'Navigate to Settings → Billing → Invoices to download a PDF copy.',
      },
      expected_action: 'ANSWER',
    },
  ];

  let passed = 0;

  for (const test of tests) {
    const result = handler.process(test.input);
    const ok = result.action === test.expected_action;
    if (ok) passed++;

    console.log(`\n${test.name}`);
    console.log(`  Expected : ${test.expected_action}`);
    console.log(`  Got      : ${result.action}  ${ok ? '✓' : '✗ FAILED'}`);
    console.log(`  Score    : ${result.breakdown.total} (match:${result.breakdown.source_match} safety:${result.breakdown.safety_check} penalty:${result.breakdown.hallucination_penalty})`);
    if (result.reason) console.log(`  Reason   : ${result.reason}`);
    if (result.hallucination_offenders?.length) {
      console.log(`  Offenders: ${result.hallucination_offenders.join(', ')}`);
    }
  }

  console.log(`\n─────────────────────────────`);
  console.log(`Results: ${passed}/${tests.length} passed`);
  console.log(`─────────────────────────────`);
}
