import { PlatformConfig } from '@/types/inbox';

export const PLATFORM_CONFIGS: Record<string, PlatformConfig> = {
  gmail: {
    platform: 'gmail',
    name: 'Gmail',
    icon: '📧',
    color: '#EA4335',
    category: 'email',
    description: 'Connect your Gmail account to sync all emails',
    features: {
      canSend: true,
      canReceive: true,
      canMarkRead: true,
      canDelete: true,
      supportsAttachments: true,
      supportsThreads: true,
      supportsWebhooks: true,
    },
    authType: 'oauth2',
    docs: 'https://developers.google.com/gmail/api',
  },
  outlook: {
    platform: 'outlook',
    name: 'Outlook',
    icon: '📨',
    color: '#0078D4',
    category: 'email',
    description: 'Connect Microsoft Outlook/365 email',
    features: {
      canSend: true,
      canReceive: true,
      canMarkRead: true,
      canDelete: true,
      supportsAttachments: true,
      supportsThreads: true,
      supportsWebhooks: true,
    },
    authType: 'oauth2',
    docs: 'https://learn.microsoft.com/en-us/graph/api/resources/mail-api-overview',
  },
  linkedin: {
    platform: 'linkedin',
    name: 'LinkedIn',
    icon: '💼',
    color: '#0A66C2',
    category: 'social',
    description: 'Sync LinkedIn messages and InMail',
    features: {
      canSend: true,
      canReceive: true,
      canMarkRead: true,
      canDelete: false,
      supportsAttachments: false,
      supportsThreads: true,
      supportsWebhooks: false,
    },
    authType: 'oauth2',
    docs: 'https://learn.microsoft.com/en-us/linkedin/marketing/integrations/community-management/messages',
  },
  whatsapp: {
    platform: 'whatsapp',
    name: 'WhatsApp',
    icon: '📱',
    color: '#25D366',
    category: 'messaging',
    description: 'Connect WhatsApp Business API',
    features: {
      canSend: true,
      canReceive: true,
      canMarkRead: true,
      canDelete: false,
      supportsAttachments: true,
      supportsThreads: false,
      supportsWebhooks: true,
    },
    authType: 'api_key',
    docs: 'https://developers.facebook.com/docs/whatsapp',
  },
  slack: {
    platform: 'slack',
    name: 'Slack',
    icon: '💬',
    color: '#4A154B',
    category: 'messaging',
    description: 'Monitor Slack DMs and mentions',
    features: {
      canSend: true,
      canReceive: true,
      canMarkRead: false,
      canDelete: false,
      supportsAttachments: true,
      supportsThreads: true,
      supportsWebhooks: true,
    },
    authType: 'oauth2',
    docs: 'https://api.slack.com/messaging',
  },
  teams: {
    platform: 'teams',
    name: 'Microsoft Teams',
    icon: '👥',
    color: '#6264A7',
    category: 'messaging',
    description: 'Sync Microsoft Teams messages',
    features: {
      canSend: true,
      canReceive: true,
      canMarkRead: true,
      canDelete: false,
      supportsAttachments: true,
      supportsThreads: true,
      supportsWebhooks: true,
    },
    authType: 'oauth2',
    docs: 'https://learn.microsoft.com/en-us/graph/api/resources/teams-api-overview',
  },
  facebook: {
    platform: 'facebook',
    name: 'Facebook Messenger',
    icon: '💙',
    color: '#1877F2',
    category: 'social',
    description: 'Connect Facebook Business Messenger',
    features: {
      canSend: true,
      canReceive: true,
      canMarkRead: true,
      canDelete: false,
      supportsAttachments: true,
      supportsThreads: true,
      supportsWebhooks: true,
    },
    authType: 'oauth2',
    docs: 'https://developers.facebook.com/docs/messenger-platform',
  },
  instagram: {
    platform: 'instagram',
    name: 'Instagram',
    icon: '📷',
    color: '#E4405F',
    category: 'social',
    description: 'Sync Instagram Business DMs',
    features: {
      canSend: true,
      canReceive: true,
      canMarkRead: true,
      canDelete: false,
      supportsAttachments: true,
      supportsThreads: true,
      supportsWebhooks: true,
    },
    authType: 'oauth2',
    docs: 'https://developers.facebook.com/docs/instagram-api',
  },
  twitter: {
    platform: 'twitter',
    name: 'Twitter/X',
    icon: '🐦',
    color: '#1DA1F2',
    category: 'social',
    description: 'Monitor Twitter/X direct messages',
    features: {
      canSend: true,
      canReceive: true,
      canMarkRead: false,
      canDelete: false,
      supportsAttachments: true,
      supportsThreads: false,
      supportsWebhooks: true,
    },
    authType: 'oauth2',
    docs: 'https://developer.twitter.com/en/docs/twitter-api',
  },
  reddit: {
    platform: 'reddit',
    name: 'Reddit',
    icon: '🤖',
    color: '#FF4500',
    category: 'social',
    description: 'Track Reddit messages and mentions',
    features: {
      canSend: true,
      canReceive: true,
      canMarkRead: true,
      canDelete: false,
      supportsAttachments: false,
      supportsThreads: true,
      supportsWebhooks: false,
    },
    authType: 'oauth2',
    docs: 'https://www.reddit.com/dev/api',
  },
  discord: {
    platform: 'discord',
    name: 'Discord',
    icon: '🎮',
    color: '#5865F2',
    category: 'messaging',
    description: 'Monitor Discord DMs and mentions',
    features: {
      canSend: true,
      canReceive: true,
      canMarkRead: false,
      canDelete: false,
      supportsAttachments: true,
      supportsThreads: false,
      supportsWebhooks: true,
    },
    authType: 'oauth2',
    docs: 'https://discord.com/developers/docs/intro',
  },
  telegram: {
    platform: 'telegram',
    name: 'Telegram',
    icon: '✈️',
    color: '#0088CC',
    category: 'messaging',
    description: 'Connect Telegram Bot API',
    features: {
      canSend: true,
      canReceive: true,
      canMarkRead: false,
      canDelete: false,
      supportsAttachments: true,
      supportsThreads: false,
      supportsWebhooks: true,
    },
    authType: 'api_key',
    docs: 'https://core.telegram.org/bots/api',
  },
  stackoverflow: {
    platform: 'stackoverflow',
    name: 'Stack Overflow',
    icon: '📚',
    color: '#F48024',
    category: 'social',
    description: 'Track Stack Overflow comments',
    features: {
      canSend: false,
      canReceive: true,
      canMarkRead: true,
      canDelete: false,
      supportsAttachments: false,
      supportsThreads: true,
      supportsWebhooks: false,
    },
    authType: 'oauth2',
    docs: 'https://api.stackexchange.com/docs',
  },
  hackernews: {
    platform: 'hackernews',
    name: 'Hacker News',
    icon: '📰',
    color: '#FF6600',
    category: 'social',
    description: 'Monitor Hacker News replies',
    features: {
      canSend: false,
      canReceive: true,
      canMarkRead: false,
      canDelete: false,
      supportsAttachments: false,
      supportsThreads: true,
      supportsWebhooks: false,
    },
    authType: 'api_key',
    docs: 'https://github.com/HackerNews/API',
  },
  quora: {
    platform: 'quora',
    name: 'Quora',
    icon: '❓',
    color: '#B92B27',
    category: 'social',
    description: 'Track Quora messages and comments',
    features: {
      canSend: false,
      canReceive: true,
      canMarkRead: false,
      canDelete: false,
      supportsAttachments: false,
      supportsThreads: true,
      supportsWebhooks: false,
    },
    authType: 'oauth2',
    docs: 'https://www.quora.com/about/api',
  },
  facebook_lead_ads: {
    platform: 'facebook_lead_ads',
    name: 'Facebook Lead Ads',
    icon: '📣',
    color: '#1877F2',
    category: 'ads',
    description: 'Capture Facebook lead form submissions',
    features: {
      canSend: false,
      canReceive: true,
      canMarkRead: true,
      canDelete: false,
      supportsAttachments: false,
      supportsThreads: false,
      supportsWebhooks: true,
    },
    authType: 'oauth2',
    docs: 'https://developers.facebook.com/docs/marketing-api/guides/lead-ads',
  },
  linkedin_lead_gen: {
    platform: 'linkedin_lead_gen',
    name: 'LinkedIn Lead Gen',
    icon: '🎯',
    color: '#0A66C2',
    category: 'ads',
    description: 'Sync LinkedIn lead generation forms',
    features: {
      canSend: false,
      canReceive: true,
      canMarkRead: true,
      canDelete: false,
      supportsAttachments: false,
      supportsThreads: false,
      supportsWebhooks: true,
    },
    authType: 'oauth2',
    docs: 'https://learn.microsoft.com/en-us/linkedin/marketing/integrations/ads/advertising-targeting/create-and-manage-lead-forms',
  },
  intercom: {
    platform: 'intercom',
    name: 'Intercom',
    icon: '💭',
    color: '#1F8DED',
    category: 'support',
    description: 'Sync Intercom conversations',
    features: {
      canSend: true,
      canReceive: true,
      canMarkRead: true,
      canDelete: false,
      supportsAttachments: true,
      supportsThreads: true,
      supportsWebhooks: true,
    },
    authType: 'api_key',
    docs: 'https://developers.intercom.com/intercom-api-reference',
  },
  zendesk: {
    platform: 'zendesk',
    name: 'Zendesk',
    icon: '🎫',
    color: '#03363D',
    category: 'support',
    description: 'Connect Zendesk support tickets',
    features: {
      canSend: true,
      canReceive: true,
      canMarkRead: true,
      canDelete: false,
      supportsAttachments: true,
      supportsThreads: true,
      supportsWebhooks: true,
    },
    authType: 'oauth2',
    docs: 'https://developer.zendesk.com/api-reference/',
  },
  twilio_sms: {
    platform: 'twilio_sms',
    name: 'Twilio SMS',
    icon: '📲',
    color: '#F22F46',
    category: 'sms',
    description: 'Send and receive SMS via Twilio',
    features: {
      canSend: true,
      canReceive: true,
      canMarkRead: false,
      canDelete: false,
      supportsAttachments: true,
      supportsThreads: false,
      supportsWebhooks: true,
    },
    authType: 'api_key',
    docs: 'https://www.twilio.com/docs/sms',
  },
};

export function getPlatformConfig(platform: string): PlatformConfig | undefined {
  return PLATFORM_CONFIGS[platform];
}

export function getAllPlatforms(): PlatformConfig[] {
  return Object.values(PLATFORM_CONFIGS);
}

export function getPlatformsByCategory(category: string): PlatformConfig[] {
  return Object.values(PLATFORM_CONFIGS).filter((p) => p.category === category);
}
